fix: respect user defined dirs

diff --git a/.local/bin/yt b/.local/bin/yt
--- a/.local/bin/yt
+++ b/.local/bin/yt
@@ -63,6 +63,12 @@ if ! command -v jq &>/dev/null; then
 	exit 1
 fi
 
+# Check if xdg-user-dir is installed
+if ! command -v xdg-user-dir &>/dev/null; then
+	echo "xdg-user-dir could not be found. Please install xdg-utils"
+	exit 1
+fi
+
 # Check if a video URL is provided
 if [ $# -ne 1 ]; then
 	echo "Usage: $(basename "$0") <video_url>"
@@ -70,7 +76,7 @@ if [ $# -ne 1 ]; then
 fi
 
 INPUT_URL="$1"
-YOUTUBE_DIR="/mnt/d/data/media/videos/youtube"
+YOUTUBE_DIR="$(xdg-user-dir VIDEOS)/youtube"
 # YOUTUBE_DIR="$HOME/yt" # used for development
 LOG_FILE="$(mktemp -d)/output.log"
 
